Fix `type.cases` part of #kaitai_struct/773
kaitai-io/ksy_schema pull request #14
Opened 2020-07-10 15:38 UTC by Mingun

@generalmimon, you say:

> This is clearly incorrect here - it allows some values that are definitely not valid (numbers) and disallows some valid values (nested `switch-on/cases`).

Do you mean that the following ksy should be allowed?
```yaml
seq:
  - type:
      switch-on: ...
      cases:
        some:
          switch-on: ...
```
That syntax currently not allowed by compiler:
> Parse error: undefined
> Call stack: undefined io.kaitai.struct.format.YAMLParseException: /seq/0/cases/some: expected string, got Map(switch-on -> 3, cases -> u1) (class scala.collection.immutable.MapLike$$anon$2)

2020-07-10 16:28 UTC, dgelessus commented
Ah, you're right, nested type switching is not allowed currently (see kaitai-io/kaitai_struct#386). In that case the schema shouldn't allow that either.

2020-07-10 16:31 UTC, dgelessus requested changes
Looks good to me for the most part, there's just one thing that I noticed that needs to be fixed.

2020-07-10 16:31 UTC, dgelessus commented on ksy_schema.json
> +          "pattern": "^([a-z][a-z0-9_]*::)*[a-z][a-z0-9_]*$"
This pattern doesn't allow type parameters. Something like this should work:

```suggestion
          "pattern": "^([a-z][a-z0-9_]*::)*[a-z][a-z0-9_]*(\\(.+\\))?$"
```

2020-07-10 16:45 UTC, Mingun commented
Done!

2020-07-10 16:57 UTC, dgelessus approved these changes

2020-07-21 08:07 UTC, merged

2020-07-21 08:08 UTC, GreyCat commented
Thanks, this is a valuable note! I actually wonder why don't we really support nested switches types, it should be easy enough...